#+TITLE: Swift 闭包

* 闭包
** 对于闭包的理解
当需要把一个函数（A）作为另一个函数（B）的参数时，
又不想不单独创建一个需要作为参数的函数，
而是直接把函数A的主体直接作为放到B函数中。
A函数就被称为闭包函数。
这样A函数就没有函数名，只有函数主题。

** 闭包表达式语法
闭合表达式语法具有以下一般构造形式：
{ (parameters) -> return type in
    statements
}

- 闭包表达式语法可以使用常量参数、变量参数和 inout 类型作为参数，但皆不可提供默认值。 如果你需要使用一个可变的参数，可将可变参数放在最后，元组类型也可以作为参数和返回值使用。

- 闭包的函数体部分由关键字 in 引入。 该关键字表示闭包的参数和返回值类型定义已经完成，闭包函数体即将开始。


** 参数名简写
对于闭包函数的每个参数，可以使用$0, $1, $2来替代



**  一种说明

[[http://www.devtalking.com/articles/closure-expressions-in-swift/][闭包]]

闭包在Swift中非常有用。通俗的解释就是一个Int类型里存储着一个整数，一个String类型包含着一串字符，同样，闭包是一个包含着函数的类型。有了闭包，你就可以处理很多在一些古老的语言中不能处理的事情。这是因为闭包使用的多样性，比如你可以将闭包赋值给一个变量，你也可以将闭包作为一个函数的参数，你甚至可以将闭包作为一个函数的返回值。它的强大之处可见一斑。

在Swift的很多文档教材中都说函数是“一等公民”，起初我还不是很理解“一等公民”是什么意思，但当我理解了闭包以及它的强大功能后，我恍然大悟、茅塞顿开、醍醐灌顶。原来闭包的这些特性就是“一等公民”的特性啊！参见维基百科First-class citizen。

Swift中的闭包类似Objective-C中的Block。其实，如果你想在Swift中实现Objective-C里的Block功能，你可以直接使用闭包来代替。Block和闭包的区别只是语法的不同而已，而且闭包的可读性比较强。

函数是闭包吗？

虽然你还没有意识到，但我们确实已经在Swift中这么用了。Swift中的函数就是闭包，在Apple的官方文档中有这样的描述：

闭包有三种形式：
1. 全局函数是一个有名字但不会捕获任何值的闭包。
2. 嵌套函数是一个有名字并可以捕获到其封闭函数域内的值的闭包。
3. 闭包表达式是一个利用轻量级语法所写的，可以捕获其上下文中变量或常量值的匿名闭包。

今天，我们要讨论的是第三种形式，尤其讨论它是如何将繁复的、可读性比较差的业务逻辑代码压缩成高可读性、简明明了的形式。

大家还记得数组的map方法么？它的参数就是一个闭包，它会将数组里的每一个元素放在闭包中进行处理，然后返回一个新的数组，甚至是与原数组不同元素类型的新数组。


#+BEGIN_SRC C
//map函数的原型如下：

func map<U>(transform: (T) -> U) -> [U]
#+END_SRC
我们可以看到该函数使用了泛型。(T) -> U是一个泛型闭包，它的意思就是类型T将会在闭包中进行逻辑处理，然后返回U类型。最后map函数会返回一个U类型的数组。

用一个例子来说明。今天我办生日聚会，要迎接很多人，并且为每个人都准备了一句欢迎词。我们要怎么做呢？首先我们将迎接的人放进一个数组名叫guestList，然后用一个名叫greetPeople的函数为每个人生成欢迎词：




#+BEGIN_SRC C
func greetPeople(person: String) -> String
{
    return "Hello, \(person)!"
}


let guestList = ["Chris", "Jill", "Tim"]
let fullGreetings = guestList.map(greetPeople)

#+END_SRC

然后将greetPeople函数作为guestList数组的map函数的参数传入，并返回一个新的数组fullGreetings，这个数组就包含了每个人的欢迎词。

如果我们想展示一下每个人的欢迎词，我们甚至可以这样写：

#+BEGIN_SRC C
fullGreetings.map(println)
#+END_SRC

这时也许有人要质疑了，println函数不是没有返回值么？那么map函数会返回什么呢？其实每一个没有返回值的函数，都会返回一个空的元组（tuple），所以说上述代码的返回值其实是Array<()>。

上面的例子中我们就是将一个全局函数greetPeople作为一个闭包来使用的。

*** 简明扼要的闭包表达式

其实Swift已经为我们提供了很多简化的语法，可以让我们保证代码的高可读性和维护性。还用上面的例子来说明，对于greetPeople这个全局函数来说，其实只需要使用一次，所以我们没必要单独定义这个函数。我们可以直接使用闭包表达式来处理：

#+BEGIN_SRC C
let fullGreetings = guestList.map({(person: String) -> String in return "Hello, \(person)!"})
#+END_SRC

闭包表达式其实是函数的字面值，官方一般称之为匿名函数。一般当我们需要使用函数快速的实现一个简短的处理逻辑并且只使用一次的时候，我们可以省去函数名，使用简化的语法。上面的代码中可以看到关键字in之前是闭包表达式的参数和返回值，in之后是闭包表达式实际处理逻辑的代码区域。

下面我们将使用Swift更多的特性来进一步简化闭包表达式。

- 我们知道Swift中有类型推断的特性，所以我们可以取掉参数类型：
#+BEGIN_SRC C
let fullGreetings = guestList.map({(person) -> String in return "Hello, \(person)!" })
#+END_SRC

- 像我们示例中的这种单一闭包表达式，编译器可以根据in之前的返回值类型和return之后的返回数据类型自动判断，所以我们可以省略返回值和return关键字：

#+BEGIN_SRC C
let fullGreetings = guestList.map({person in "Hello, \(person)!" })
#+END_SRC

- 其实在Swift中还提供了参数的简写方式：$0代表第一个参数、$1代表第二个参数以此类推。所以我们又可以将参数名称省略：

#+BEGIN_SRC C
let fullGreetings = guestList.map({ "Hello, \($0)!" })
#+END_SRC

- 当函数的最后一个参数是闭包时，可以将闭包写在()之外，这也是Swift的一个特性，所以我们还可以继续简化：

#+BEGIN_SRC C
let fullGreetings = guestList.map(){ "Hello, \($0)!" }
#+END_SRC

- 当函数有且仅有一个参数，并该参数是闭包时，不但可以将闭包写在()外，还可以省略()：

#+BEGIN_SRC C
let fullGreetings = guestList.map{ "Hello, \($0)!" }
#+END_SRC

到目前为止，示例中的闭包表达式已经被我们根据Swift的特性，简化为简明扼要、高可读性的闭包表达式了，是不是很酷呢！